### PR TITLE
Fixed bug which occured after merge; removed duplicate cors statement

### PR DESCRIPTION
**Pull request by thestahan**

### CODE REVIEW

**Review by WojciechGrochalski — CHANGES_REQUESTED** [review]
this policy must stay

**Comment by thestahan** [comment]
The policy stays. It's defined in ConfigureServices and then used below by calling app.UseCors("CorsPolicy");

**Review by hax33l — APPROVED** [review]
Works for me.
The bug, no longer occurs.

**Comment by WojciechGrochalski** [comment]
> The policy stays. It's defined in ConfigureServices and then used below by calling app.UseCors("CorsPolicy");
Zrzut ekranu 2021-04-27 114057

**Review by WojciechGrochalski — APPROVED** [review]

**Pull request merged**
